language: csharp

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y build-essential
- sudo apt-get install python 

script:
  - cd HouseKeeping
  - make mono
  - cd ..
  - make -f makefile all

after_script:
  - cd UnitTests/compile-test
  - ls
  - make -f all
  - cd ../runtime-test/C
  - ls
  - make -f all
